# handle_unknown deny
class CLASS1
class CLASS2
class CLASS3
sid kernel
class CLASS1 { PERM1 }
bool BOOL1 true;
type TYPE1;
type TYPE2;
type TYPE3;
allow TYPE1 self:CLASS1 { PERM1 };
type_transition TYPE1 TYPE1:CLASS1 TYPE2;
type_transition TYPE1 TYPE1:CLASS1 TYPE3 "basename_default";
optional {
type_transition TYPE1 TYPE1:CLASS2 TYPE2;
type_transition TYPE1 TYPE1:CLASS2 TYPE3 "basename_optional";
}
if (BOOL1) {
    type_transition TYPE1 TYPE1:CLASS3 TYPE2;
    type_transition TYPE1 TYPE1:CLASS3 TYPE3 "basename_conditional";
}
role ROLE1;
role ROLE1 types { TYPE1 };
user USER1 roles ROLE1;
sid kernel USER1:ROLE1:TYPE1
